# See the detailed configuration at
# https://golangci-lint.run/usage/configuration

# Options for analysis running.
run:
  # The default concurrency value is the number of available CPU.
  concurrency: 2

# output configuration options
output:

# All available settings of specific linters.
linters-settings:

linters:

issues:

severity:

