run:
  timeout: 10m
  skip-dirs-use-default: true
  tests: true
output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  severity-sort: false
linters-settings:
  govet:
    check-shadowing: true
  gosimple:
    skip-unexported: true
  unused:
    check-exported: true
  prealloc:
    maxSize: 100
linters:
  enable:
    - gofmt
    - goimports
    - golint
    - gosec
    - govet
    - ineffassign
    - staticcheck
    - structcheck
    - unused
  disable:
    - gocognit
    - gomnd
issues:
  exclude-rules:
    - exportloopref
severity:
  error: "error"
  warning: "warning"

#Alerta: Código gerado pelo "estagiario". Nome do estagiario "ChatGPT3".