# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  # Optional: allow read access to pull request. Use with `only-new-issues` option.
  pull-requests: read

env:
  GO_VERSION: '1.19'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ env.GO_VERSION }}

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

    - name: Lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: latest
        only-new-issues: true
        skip-cache: true
        skip-build-cache: true
        skip-pkg-cache: true

    - name: Scan for Vulnerabilities in Code
      uses: Templum/govulncheck-action@<version>
      with:
        go-version: ${{ env.GO_VERSION }}
        version: latest
        package: ./...
        fail-on-vuln: true